import { creaCapitolo, check, riga } from "../factory.js";

export default creaCapitolo({
    id: "ch09", num: 9, requires: ["ch08"],
    title: { it: "Web/PHP: path traversal", en: "Web/PHP: path traversal" },
    oneLiner: { it: "Un nome di file controllato dall'utente può diventare un percorso fuori dall'app.", en: "A user-controlled filename can become a path outside the app." },
    commands: ["curl --get", "cyber-harden traversal", "realpath"], glossary: ["path traversal", "allowlist", "HTTP 403"],
    hook: { it: "Il server voleva mostrare un documento; l'attaccante gli chiede invece un file di sistema. La funzione di lettura fa esattamente ciò che le è stato detto.", en: "The server meant to show a document; the attacker asks it for a system file instead. The read function does exactly what it was told." },
    lead: { it: "Il seme crea un segreto con nome imprevedibile sotto <code>/etc/cyber-lab</code> e consegna il percorso all'attaccante. In stato vulnerabile <code>/file</code> lo legge; dopo la correzione lo stesso URL deve ricevere 403.", en: "The seed creates an unpredictable secret under <code>/etc/cyber-lab</code> and gives the path to the attacker. In vulnerable state <code>/file</code> reads it; after the fix the same URL must receive 403." },
    analogy: { it: "Un addetto all'archivio riceve un codice pratica, non le coordinate complete di qualunque scaffale dell'edificio.", en: "An archive clerk should receive a case ID, not complete coordinates for every shelf in the building." },
    shown: [{ cmd: "curl -G --data-urlencode 'name=/etc/passwd' http://10.10.0.2:8080/file", out: "root:x:0:0:root:/root:/bin/bash", note: { it: "La lettura avviene sul difensore, la risposta torna all'attaccante.", en: "Reading happens on the defender and the response returns to the attacker." } }, { cmd: "curl -o /dev/null -w '%{http_code}' ...", out: "403", note: { it: "Dopo il fix lo stesso percorso è negato.", en: "After the fix the same path is denied." } }],
    pitfalls: [{ it: "<strong>Bloccare soltanto <code>../</code> non basta.</strong> Percorsi assoluti, codifiche e link simbolici chiedono una radice consentita e un percorso canonico.", en: "<strong>Blocking only <code>../</code> is not enough.</strong> Absolute paths, encodings, and symlinks require an allowed root and canonical path." }, { it: "Cambiare nome al file segreto nasconde questa istanza, non chiude la lettura arbitraria.", en: "Renaming the secret hides this instance; it does not close arbitrary reading." }],
    pro: { it: "<p>Il router didattico usa un interruttore netto per rendere misurabile l'invariante. In produzione il pattern è: identificatore opaco → lookup server-side, oppure <code>realpath</code> seguito dalla verifica che il risultato resti sotto una directory consentita.</p>", en: "<p>The teaching router uses a crisp switch to make the invariant measurable. In production the pattern is: opaque ID → server-side lookup, or <code>realpath</code> followed by checking the result remains beneath an allowed directory.</p>" },
    exercise: {
        brief: { it: "Leggi il percorso seminato in <code>~/lab/secret-path.txt</code>, osserva che l'attacco funziona, poi abilita l'hardening traversal sul difensore.", en: "Read the seeded path in <code>~/lab/secret-path.txt</code>, observe the attack working, then enable traversal hardening on the defender." },
        come: [{ dove: "pc", testo: { it: "Dimostra prima la falla:", en: "Prove the flaw first:" }, cmd: "curl -G --data-urlencode \"name=$(cat ~/lab/secret-path.txt)\" http://10.10.0.2:8080/file" }, { dove: "server", testo: { it: "Chiudi la lettura arbitraria:", en: "Close arbitrary reading:" }, cmd: "cyber-harden traversal" }, { dove: "pc", testo: { it: "Ripeti identica la richiesta e osserva 403:", en: "Repeat the identical request and observe 403:" }, cmd: "curl -o /dev/null -w '%{http_code}\\n' -G --data-urlencode \"name=$(cat ~/lab/secret-path.txt)\" http://10.10.0.2:8080/file" }],
        nota: { it: "Il verde non cerca il comando: invia il percorso segreto e misura codice 403 più assenza del valore nella risposta.", en: "Green does not search the command: it sends the secret path and measures status 403 plus absence of the value in the response." },
        checks: [check("traversal-negato", "Il percorso arbitrario non riceve HTTP 403.", "The arbitrary path does not receive HTTP 403.", "Abilita <code>cyber-harden traversal</code> sul difensore.", "Enable <code>cyber-harden traversal</code> on the defender."), check("segreto-non-esce", "Il valore segreto compare ancora nella risposta dell'attaccante.", "The secret value still appears in the attacker response.", "Non basta cambiare il codice HTTP: interrompi davvero la lettura.", "Changing HTTP status is not enough: actually stop the read.")],
        hints: [{ it: "Il nome cambia col mondo; usa sempre il file seminato.", en: "The name changes with the world; always use the seeded file." }, { it: "<code>--data-urlencode</code> conserva slash e caratteri speciali.", en: "<code>--data-urlencode</code> preserves slashes and special characters." }],
    },
    recap: [riga("realpath + radice", "confina le letture", "confine reads", "verifica il prefisso canonico", "check canonical prefix"), riga("HTTP 403", "nega intenzionalmente", "deny intentionally", "nessun contenuto segreto", "no secret content")],
});
