import { creaCapitolo, check, riga } from "../factory.js";

export default creaCapitolo({
    id: "ch06", num: 6, requires: ["ch05"],
    title: { it: "fail2ban: il ban è la prova", en: "fail2ban: the ban is the proof" },
    oneLiner: { it: "Il processo attivo non conta: contano l'IP nel registro e l'attaccante tagliato fuori.", en: "The active process does not count: the IP in the register and the locked-out attacker do." },
    commands: ["fail2ban-client", "cyber-burst", "iptables -L"], glossary: ["jail", "maxretry", "ban"],
    hook: { it: "<code>active</code> descrive un processo, non una difesa. Un filtro cieco può essere attivo per mesi senza bloccare un solo pacchetto.", en: "<code>active</code> describes a process, not a defense. A blind filter may be active for months without blocking one packet." },
    lead: { it: "La jail <code>cyber-auth</code> osserva il registro dell'app e usa iptables nel namespace del difensore. Abilitala. La verifica parte da una porta raggiungibile, genera la raffica e pretende due effetti: IP bannato e porta non più raggiungibile.", en: "Jail <code>cyber-auth</code> watches the app log and uses iptables in the defender namespace. Enable it. The check starts from a reachable port, generates the burst, and requires two effects: banned IP and no more reachability." },
    analogy: { it: "Un guardiano in uniforme è «attivo». La prova del suo lavoro è il nome nel registro degli esclusi e la persona che resta fuori.", en: "A guard in uniform is “active”. Proof of the job is the name in the exclusion register and the person kept outside." },
    shown: [{ cmd: "sudo fail2ban-client status cyber-auth", out: "Currently banned: 1\nBanned IP list: 10.10.0.1", note: { it: "È il primo testimone, ma non basta senza la sonda dopo il ban.", en: "This is the first witness, but it is not enough without the post-ban probe." } }, { cmd: "curl --max-time 3 http://10.10.0.2:8080/health", out: "curl: (7) Failed to connect", note: { it: "Lo stesso attaccante ora è fuori.", en: "The same attacker is now outside." } }],
    pitfalls: [{ it: "<strong>Non verificare <code>systemctl is-active</code> o l'equivalente OpenRC.</strong> Sarebbe precisamente la falsa sicurezza che il capitolo corregge.", en: "<strong>Do not check <code>systemctl is-active</code> or its OpenRC equivalent.</strong> That would be exactly the false confidence this chapter corrects." }, { it: "Bannare <code>127.0.0.1</code> o un gateway non prova nulla: la LAN diretta conserva <code>10.10.0.1</code>.", en: "Banning <code>127.0.0.1</code> or a gateway proves nothing: the direct LAN preserves <code>10.10.0.1</code>." }],
    pro: { it: "<p>fail2ban è quello reale, avviato dentro i namespace rete e UTS del difensore. La sua azione crea una catena iptables lì; avviarlo dal lato sbagliato produrrebbe un ban corretto in una pila di rete che non vede i pacchetti.</p>", en: "<p>This is real fail2ban, started inside the defender's network and UTS namespaces. Its action creates an iptables chain there; starting it on the wrong side would create a correct ban in a network stack that never sees the packets.</p>" },
    exercise: {
        brief: { it: "Sul difensore abilita la jail <code>cyber-auth</code> in <code>/etc/fail2ban/jail.d/cyber-lab.conf</code>. Non devi lanciare tu la raffica: la verifica sarà l'attaccante.", en: "On the defender, enable jail <code>cyber-auth</code> in <code>/etc/fail2ban/jail.d/cyber-lab.conf</code>. Do not fire the burst yourself: the check will be the attacker." },
        come: [{ dove: "server", testo: { it: "Modifica soltanto l'abilitazione:", en: "Change only the enable switch:" }, cmd: "sudo sed -i 's/enabled = false/enabled = true/' /etc/fail2ban/jail.d/cyber-lab.conf" }, { dove: "server", testo: { it: "Puoi controllare la configurazione, ma il verde arriverà solo dall'attacco:", en: "You may inspect the configuration, but green will only come from the attack:" }, cmd: "sudo fail2ban-client -t" }],
        nota: { it: "Il check conferma la baseline, invia cinque login falliti, prova gli eventi nel registro del difensore e li consegna all'API <code>attempt</code> di Fail2ban (necessaria perché v86 non consegna in modo affidabile gli eventi filesystem). Il verde copre il ban reale e il suo effetto iptables; il capitolo 7 copre il filtro. Non legge lo stato del servizio.", en: "The check confirms the baseline, sends five failed logins, proves the events in the defender log, and hands them to Fail2ban's <code>attempt</code> API (needed because v86 does not deliver filesystem events reliably). Green covers the real ban and its iptables effect; chapter 7 covers the filter. It does not read service activity." },
        checks: [check("baseline-raggiungibile", "La porta era già irraggiungibile prima dell'attacco: la prova non è valida.", "The port was already unreachable before the attack: the proof is invalid.", "Ricomincia per ripulire le vecchie regole.", "Restart to clear old rules."), check("ip-bannato", "Nel registro dei ban non compare 10.10.0.1 dopo la raffica.", "10.10.0.1 is absent from the ban register after the burst.", "Controlla filtro, logpath e <code>enabled</code>.", "Check filter, logpath, and <code>enabled</code>."), check("ban-efficace", "Dopo il ban l'attaccante raggiunge ancora la porta 8080.", "After the ban, the attacker can still reach port 8080.", "Il demone deve vivere nel namespace del difensore; usa la configurazione fornita.", "The daemon must live in the defender namespace; use the supplied configuration.")],
        hints: [{ it: "La soglia è già configurata: l'unica modifica richiesta è <code>enabled = true</code>.", en: "The threshold is already configured: the only requested change is <code>enabled = true</code>." }, { it: "Non aggiungere un ban a mano: il check cambia token e genera eventi nuovi.", en: "Do not add a ban by hand: the check changes the token and generates fresh events." }],
    },
    recap: [riga("fail2ban-client status jail", "mostra il registro dei ban", "show the ban register", "cerca l'IP reale", "look for the real IP"), riga("attacco dopo il ban", "prova l'effetto sui pacchetti", "prove the packet effect", "stessa sorgente", "same source")],
});
