import { creaCapitolo, check, riga } from "../factory.js";

export default creaCapitolo({
    id: "ch05", num: 5, requires: ["ch04"],
    title: { it: "La raffica", en: "The burst" },
    oneLiner: { it: "Prima del ban serve un evento osservabile: N tentativi, N righe, IP vero.", en: "Before a ban there must be an observable event: N attempts, N lines, real IP." },
    commands: ["cyber-burst", "grep -c", "tail"], glossary: ["raffica", "evento", "sorgente"],
    hook: { it: "Una difesa automatica non può reagire a ciò che non viene registrato. Prima si misura il segnale, poi si costruisce la reazione.", en: "An automated defense cannot react to what is not recorded. Measure the signal first, then build the reaction." },
    lead: { it: "Il seme sceglie un numero di tentativi e un token. <code>cyber-burst</code> manda richieste HTTP fallite dal vero IP <code>10.10.0.1</code>; l'applicazione del difensore registra una riga per colpo.", en: "The seed chooses an attempt count and token. <code>cyber-burst</code> sends failed HTTP requests from real IP <code>10.10.0.1</code>; the defender application records one line per hit." },
    analogy: { it: "Un allarme che dice «molto rumore» non è tarato. Cinque colpi devono diventare cinque eventi, altrimenti soglia e risposta poggiano sul caso.", en: "An alarm saying “lots of noise” is not calibrated. Five hits must become five events, or threshold and response rest on chance." },
    shown: [{ cmd: "cyber-burst 5 prova", out: "5 tentativi inviati a 10.10.0.2", note: { it: "L'helper rifiuta altri bersagli e più di 20 tentativi.", en: "The helper rejects other targets and more than 20 attempts." } }, { cmd: "grep -c 'Failed login' /var/log/cyber-lab/audit.log", out: "5", note: { it: "Il conteggio vive sul difensore.", en: "The count lives on the defender." } }],
    pitfalls: [{ it: "<strong>Il numero stampato dall'attaccante non è il testimone.</strong> Dice quanti invii ha tentato, non quanti il difensore ha ricevuto.", en: "<strong>The number printed by the attacker is not the witness.</strong> It says how many sends were attempted, not how many the defender received." }, { it: "Contare tutte le righe mescola mondi e token. Si filtra l'identificatore seminato.", en: "Counting all lines mixes worlds and tokens. Filter the seeded identifier." }],
    pro: { it: "<p>La verifica aggiunge una sonda con un token separato e controlla che il contatore aumenti esattamente di uno. Così prova anche il sensore, senza regalare il risultato dell'esercizio.</p>", en: "<p>The check adds one probe with a separate token and checks that the counter increases by exactly one. This also tests the sensor without giving away the exercise result.</p>" },
    exercise: {
        brief: { it: "Su attacker leggi <code>~/lab/burst.env</code>, lancia esattamente quel numero di tentativi col token indicato e controlla il registro dal difensore.", en: "On attacker, read <code>~/lab/burst.env</code>, send exactly that many attempts with the indicated token, and inspect the defender log." },
        come: [{ dove: "pc", testo: { it: "Carica i due valori e lancia:", en: "Load both values and fire:" }, cmd: ". ~/lab/burst.env\ncyber-burst \"$N\" \"$TOKEN\"" }, { dove: "server", testo: { it: "Conta soltanto quel token:", en: "Count only that token:" }, cmd: "sudo grep \"token=$TOKEN\" /var/log/cyber-lab/audit.log" }],
        nota: { it: "N e token cambiano col seme. Il check pretende N righe, tutte attribuite a <code>10.10.0.1</code>.", en: "N and token change with the seed. The check requires N lines, all attributed to <code>10.10.0.1</code>." },
        checks: [check("tentativi-registrati", "Il difensore non ha registrato esattamente N tentativi di questo mondo.", "The defender did not record exactly N attempts for this world.", "Rileggi <code>burst.env</code> e non rilanciare due volte.", "Read <code>burst.env</code> again and do not run the burst twice."), check("ip-sorgente-vero", "Le righe non riportano il vero IP dell'attaccante.", "The lines do not report the attacker's real IP.", "Guarda il campo dopo <code>from</code> nel registro del difensore.", "Inspect the field after <code>from</code> in the defender log."), check("sensore-vivo", "La sonda di verifica non ha prodotto una nuova riga.", "The verification probe did not produce a new line.", "Controlla che la porta 8080 sia raggiungibile.", "Check that port 8080 is reachable.")],
        hints: [{ it: "Il file è shell valida: il punto iniziale importa N e TOKEN.", en: "The file is valid shell: the leading dot imports N and TOKEN." }, { it: "Se hai lanciato due volte, premi Ricomincia: il registro viene azzerato.", en: "If you ran twice, press Restart: the log will be cleared." }],
    },
    recap: [riga("cyber-burst N TOKEN", "genera N fallimenti reali", "generate N real failures", "solo 10.10.0.2", "10.10.0.2 only"), riga("grep -c", "misura eventi sul difensore", "measure events on the defender", "filtra per token", "filter by token")],
});
