import { creaCapitolo, check, riga } from "../factory.js";

export default creaCapitolo({
    id: "ch08", num: 8, requires: ["ch07"],
    title: { it: "Web/PHP: XSS riflesso", en: "Web/PHP: reflected XSS" },
    oneLiner: { it: "La correzione è dimostrata quando lo stesso payload torna come testo, non come markup.", en: "The fix is proven when the same payload returns as text, not markup." },
    commands: ["curl --get", "cyber-harden xss", "htmlspecialchars"], glossary: ["XSS", "escaping", "contesto HTML"],
    hook: { it: "Stampare input non fidato dentro HTML trasforma una stringa in istruzioni per il browser. Il bug non è il carattere <code>&lt;</code>: è il contesto non rispettato.", en: "Printing untrusted input inside HTML turns a string into browser instructions. The bug is not the <code>&lt;</code> character: it is failing to respect context." },
    lead: { it: "L'endpoint <code>/echo</code> riflette un payload seminato. Prima il tag torna intatto; dopo l'hardening deve comparire codificato. La verifica invia il payload dalla macchina attaccante entrambe le volte previste dal banco.", en: "Endpoint <code>/echo</code> reflects a seeded payload. Before hardening the tag returns intact; afterwards it must be encoded. The check sends the payload from the attacker machine in both bench states." },
    analogy: { it: "Copiare una frase su un cartello è diverso dal consegnarla come istruzione alla tipografia. L'escaping dice: «questi segni sono testo».", en: "Copying a sentence onto a sign differs from handing it in as printing instructions. Escaping says: “these symbols are text.”" },
    shown: [{ cmd: "curl -G --data-urlencode 'msg=<script>probe</script>' http://10.10.0.2:8080/echo", out: "&lt;script&gt;probe&lt;/script&gt;", note: { it: "Il significato è conservato, l'esecuzione no.", en: "Meaning is preserved, execution is not." } }],
    pitfalls: [{ it: "<strong>Rimuovere la parola <code>script</code> non risolve XSS.</strong> Esistono molti elementi e contesti; serve codificare per il contesto di uscita.", en: "<strong>Removing the word <code>script</code> does not fix XSS.</strong> Many elements and contexts exist; encode for the output context." }, { it: "Un WAF che blocca questo solo payload copre questo test, non ogni XSS. Un verde vale per ciò che misura.", en: "A WAF blocking this one payload covers this test, not every XSS. Green means only what was measured." }],
    pro: { it: "<p>L'app PHP è vera, su i386 dentro v86. Il fix usa <code>htmlspecialchars(..., ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8')</code>. Questo è corretto per testo HTML; attributi, URL, JavaScript e CSS richiedono contesti diversi.</p>", en: "<p>This is a real PHP app, on i386 inside v86. The fix uses <code>htmlspecialchars(..., ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8')</code>. This is correct for HTML text; attributes, URLs, JavaScript, and CSS require different contexts.</p>" },
    exercise: {
        brief: { it: "Sul difensore abilita l'hardening XSS, poi riprova dal lato attaccante con il payload in <code>~/lab/xss.txt</code>.", en: "On the defender enable XSS hardening, then retry from the attacker side with the payload in <code>~/lab/xss.txt</code>." },
        come: [{ dove: "server", testo: { it: "Attiva la correzione dell'output HTML:", en: "Enable HTML output hardening:" }, cmd: "cyber-harden xss" }, { dove: "pc", testo: { it: "Invia il payload senza perderne i caratteri:", en: "Send the payload without losing characters:" }, cmd: "curl -G --data-urlencode \"msg=$(cat ~/lab/xss.txt)\" http://10.10.0.2:8080/echo" }],
        nota: { it: "Il check manda il payload seminato e pretende che la risposta non contenga il tag grezzo ma contenga la versione codificata.", en: "The check sends the seeded payload and requires the response not to contain the raw tag but to contain its encoded form." },
        checks: [check("xss-non-eseguibile", "Il payload torna ancora come markup grezzo.", "The payload still returns as raw markup.", "Attiva l'hardening XSS sul difensore.", "Enable XSS hardening on the defender."), check("testo-conservato", "La difesa ha cancellato il contenuto invece di renderlo innocuo.", "The defense deleted the content instead of making it harmless.", "La risposta deve contenere <code>&amp;lt;</code> e <code>&amp;gt;</code>.", "The response should contain <code>&amp;lt;</code> and <code>&amp;gt;</code>.")],
        hints: [{ it: "Il flag vive sul difensore; il payload parte dall'attaccante.", en: "The flag lives on the defender; the payload leaves from the attacker." }, { it: "Guarda la risposta completa di curl, non solo il codice HTTP.", en: "Inspect the full curl response, not only the HTTP status." }],
    },
    recap: [riga("htmlspecialchars", "rende testo sicuro nel corpo HTML", "make text safe in HTML body", "ENT_QUOTES + UTF-8", "ENT_QUOTES + UTF-8"), riga("stesso payload", "prova il prima/dopo", "prove before/after", "non cambiare la sonda", "do not change the probe")],
});
