import { creaCapitolo, check, riga } from "../factory.js";

export default creaCapitolo({
    id: "ch04", num: 4, requires: ["ch03"],
    title: { it: "Le tre fasce: pubblico, interno, mai", en: "Three zones: public, internal, never" },
    oneLiner: { it: "Non tutte le porte aperte hanno lo stesso pubblico.", en: "Not every open port has the same audience." },
    commands: ["iptables", "curl --interface", "nc -s"], glossary: ["zona", "allowlist", "default deny"],
    hook: { it: "Un sito pubblico, una dashboard d'ufficio e un database possono essere tutti accesi. La difesa corretta non dà loro la stessa rete.", en: "A public site, an office dashboard, and a database may all be running. Correct defense does not give them the same network." },
    lead: { it: "Il difensore ascolta su 80, 9090 e 3306. L'attaccante possiede due indirizzi di prova: <code>.1</code> è esterno, <code>.3</code> rappresenta la fascia fidata. Configura una matrice di accesso, poi lascia parlare le sonde.", en: "The defender listens on 80, 9090, and 3306. The attacker owns two test addresses: <code>.1</code> is external, <code>.3</code> represents the trusted zone. Configure an access matrix, then let probes speak." },
    analogy: { it: "L'atrio è pubblico, l'ufficio richiede un badge, il caveau non ha ingresso dalla strada. «Server acceso» non decide nessuna delle tre politiche.", en: "The lobby is public, the office requires a badge, and the vault has no street entrance. “Server running” decides none of those policies." },
    shown: [{ cmd: "curl --interface 10.10.0.3 http://10.10.0.2:9090", out: "CYBER-LAB SERVICE", note: { it: "La stessa porta rifiuta la sorgente <code>.1</code>.", en: "The same port rejects source <code>.1</code>." } }],
    pitfalls: [{ it: "<strong>Consentire tutta la /24 non crea una fascia interna.</strong> In questo mondo anche l'attaccante è sulla /24: la fiducia va resa esplicita.", en: "<strong>Allowing the whole /24 does not create an internal zone.</strong> In this world the attacker is on that /24 too: trust must be explicit." }, { it: "Bloccare 3306 spegnendolo cancella la distinzione fra esposizione e disponibilità.", en: "Blocking 3306 by stopping it erases the distinction between exposure and availability." }],
    pro: { it: "<p>Gli alias <code>10.10.0.1</code> e <code>.3</code> condividono la stessa interfaccia, ma il kernel mette davvero i rispettivi indirizzi nei pacchetti. Il firewall decide su quei campi reali.</p>", en: "<p>Aliases <code>10.10.0.1</code> and <code>.3</code> share one interface, but the kernel really places their respective addresses in packets. The firewall decides on those real fields.</p>" },
    exercise: {
        brief: { it: "Nella catena <code>EDU-ZONES</code>: porta 80 a tutti; 9090 soltanto a <code>10.10.0.3</code>; 3306 a nessuno. I servizi devono restare accesi.", en: "In chain <code>EDU-ZONES</code>: port 80 for everyone; 9090 only for <code>10.10.0.3</code>; 3306 for nobody. Services must stay running." },
        come: [
            { dove: "server", testo: { it: "Consenti la porta pubblica:", en: "Allow the public port:" }, cmd: "sudo iptables -A EDU-ZONES -p tcp --dport 80 -j ACCEPT" },
            { dove: "server", testo: { it: "Consenti prima la sorgente fidata sulla dashboard:", en: "First allow the trusted source to the dashboard:" }, cmd: "sudo iptables -A EDU-ZONES -s 10.10.0.3 -p tcp --dport 9090 -j ACCEPT" },
            { dove: "server", testo: { it: "Rifiuta le altre sorgenti sulla dashboard:", en: "Reject other sources from the dashboard:" }, cmd: "sudo iptables -A EDU-ZONES -p tcp --dport 9090 -j REJECT" },
            { dove: "server", testo: { it: "Rifiuta ogni accesso di rete al database:", en: "Reject all network access to the database:" }, cmd: "sudo iptables -A EDU-ZONES -p tcp --dport 3306 -j REJECT" },
        ],
        nota: { it: "Il check lancia quattro connessioni reali, comprese le due sorgenti diverse verso la dashboard.", en: "The check launches four real connections, including both different source addresses toward the dashboard." },
        checks: [check("pubblico-aperto", "La porta pubblica 80 non è raggiungibile.", "Public port 80 is not reachable.", "La prima regola deve accettare 80.", "The first rule should accept 80."), check("interno-fidato", "La sorgente fidata .3 non raggiunge la dashboard.", "Trusted source .3 cannot reach the dashboard.", "Metti l'ACCEPT specifico prima del rifiuto generale.", "Put the specific ACCEPT before the general reject."), check("interno-negato", "La sorgente esterna .1 raggiunge la dashboard.", "External source .1 reaches the dashboard.", "Dopo l'eccezione aggiungi il rifiuto per 9090.", "After the exception, add the reject for 9090."), check("mai-negato", "Il database 3306 è ancora raggiungibile dalla rete.", "Database 3306 is still reachable from the network.", "Il processo deve restare vivo; filtra la porta.", "The process must remain alive; filter the port.")],
        hints: [{ it: "iptables legge le regole dall'alto: l'ordine è parte della politica.", en: "iptables reads rules top to bottom: order is part of the policy." }, { it: "Verifica i listener con <code>ss -tln</code> prima di accusare il firewall.", en: "Check listeners with <code>ss -tln</code> before blaming the firewall." }],
    },
    recap: [riga("ACCEPT specifico", "apre la fascia necessaria", "open the required zone", "prima del rifiuto", "before the reject"), riga("REJECT generale", "chiude ciò che resta", "close what remains", "servizio ancora vivo", "service still alive")],
});
