import { creaCapitolo, check, riga } from "../factory.js";

export default creaCapitolo({
    id: "ch11", num: 11, requires: ["ch10"],
    title: { it: "Chi è il testimone credibile", en: "Who is the credible witness" },
    oneLiner: { it: "La history racconta intenzioni; il registro del difensore racconta effetti ricevuti.", en: "History records intentions; the defender log records received effects." },
    commands: ["curl", "tail", "grep", "history -c"], glossary: ["testimone", "audit", "catena delle prove"],
    hook: { it: "L'attaccante può cancellare la propria history, inventarla o non averla mai salvata. Non può retroattivamente impedire al difensore di aver ricevuto il pacchetto.", en: "The attacker can erase their history, fabricate it, or never save it. They cannot retroactively stop the defender from having received the packet." },
    lead: { it: "Il seme consegna un marcatore unico. Invialo a <code>/witness</code>, poi cancella la history: l'esercizio deve restare verificabile dal registro remoto con marcatore e IP sorgente.", en: "The seed provides a unique marker. Send it to <code>/witness</code>, then clear history: the exercise must remain verifiable from the remote log with marker and source IP." },
    analogy: { it: "La tua agenda dice che volevi entrare in banca. La telecamera della banca dice che sei arrivato alla porta. Per provare l'evento serve il secondo testimone.", en: "Your diary says you meant to enter the bank. The bank camera says you reached the door. Proving the event requires the second witness." },
    shown: [{ cmd: "sudo tail -1 /var/log/cyber-lab/audit.log", out: "WITNESS ip=10.10.0.1 marker=...", note: { it: "Sorgente, evento e valore osservati dal destinatario.", en: "Source, event, and value observed by the recipient." } }, { cmd: "history -c", out: "", note: { it: "La prova sul difensore resta.", en: "The evidence on the defender remains." } }],
    pitfalls: [{ it: "<strong>Fare grep nella history premia la forma del comando.</strong> Un alias, uno script o un client diverso produrrebbero lo stesso evento reale.", en: "<strong>Grepping shell history rewards command form.</strong> An alias, script, or different client would produce the same real event." }, { it: "Un log locale non è infallibile: può essere alterato da chi controlla il difensore. Qui è credibile rispetto alla domanda limitata «il destinatario ha visto la sonda?».", en: "A local log is not infallible: whoever controls the defender can alter it. Here it is credible for the limited question “did the recipient see the probe?”" }],
    pro: { it: "<p>Una prova ha sempre uno scope. Questo verde dimostra che l'app sul difensore ha ricevuto un marker dal vero IP dell'attaccante e che una seconda sonda di controllo attraversa ancora la pipeline. Non dimostra immutabilità forense né attribuzione a una persona.</p>", en: "<p>Evidence always has scope. This green proves the defender app received a marker from the attacker's real IP and that a second control probe still crosses the pipeline. It does not prove forensic immutability or attribution to a person.</p>" },
    exercise: {
        brief: { it: "Da attacker invia il marcatore in <code>~/lab/witness.txt</code> a <code>/witness</code>. Poi puoi cancellare la history: il verde non la leggerà.", en: "From attacker send the marker in <code>~/lab/witness.txt</code> to <code>/witness</code>. You may then clear history: green will not read it." },
        come: [{ dove: "pc", testo: { it: "Invia l'evento:", en: "Send the event:" }, cmd: "curl -G --data-urlencode \"marker=$(cat ~/lab/witness.txt)\" http://10.10.0.2:8080/witness" }, { dove: "pc", testo: { it: "Cancella pure la traccia locale:", en: "Go ahead and erase the local trace:" }, cmd: "history -c" }, { dove: "server", testo: { it: "Leggi il testimone che conta:", en: "Read the witness that matters:" }, cmd: "sudo tail /var/log/cyber-lab/audit.log" }],
        nota: { it: "Il check ignora completamente <code>~/.bash_history</code>. Pretende il marker nel log del difensore con IP 10.10.0.1, poi invia un secondo marker di controllo.", en: "The check completely ignores <code>~/.bash_history</code>. It requires the marker in the defender log with IP 10.10.0.1, then sends a second control marker." },
        checks: [check("evento-nel-difensore", "Il marcatore non compare nel registro del destinatario.", "The marker is absent from the recipient log.", "Invialo davvero a <code>/witness</code> dalla macchina sinistra.", "Actually send it to <code>/witness</code> from the left machine."), check("sorgente-credibile", "L'evento non è attribuito al vero IP 10.10.0.1.", "The event is not attributed to real IP 10.10.0.1.", "Non scrivere il log a mano dal terminale destro.", "Do not write the log by hand from the right terminal."), check("pipeline-viva", "La sonda di controllo non raggiunge il registro.", "The control probe does not reach the log.", "Lascia la porta 8080 e il servizio attivi.", "Keep port 8080 and the service running." )],
        hints: [{ it: "La risposta <code>SEEN</code> dice che l'app ha ricevuto il marker; il log aggiunge la sorgente.", en: "Response <code>SEEN</code> says the app received the marker; the log adds its source." }, { it: "La history è una pista utile per te, non l'oracolo dell'esercizio.", en: "History is a useful clue for you, not the exercise oracle." }],
    },
    recap: [riga("registro difensore", "testimonia l'effetto ricevuto", "witness the received effect", "IP + marker", "IP + marker"), riga("history attaccante", "racconta comandi locali", "record local commands", "utile, non probante", "useful, not proof")],
});
