import { creaCapitolo, check, riga } from "../factory.js";

export default creaCapitolo({
    id: "ch10", num: 10, requires: ["ch09"],
    title: { it: "Web/PHP: esecuzione di comandi", en: "Web/PHP: command execution" },
    oneLiner: { it: "Prima l'attaccante ottiene l'identità del processo web; dopo non ottiene alcuna esecuzione.", en: "First the attacker obtains the web process identity; afterwards no execution occurs." },
    commands: ["curl --get", "id", "cyber-harden rce"], glossary: ["RCE", "processo web", "shell"],
    hook: { it: "Quando una stringa HTTP arriva a una shell, l'attaccante non sta più parlando con l'applicazione: sta dando ordini al sistema operativo.", en: "When an HTTP string reaches a shell, the attacker is no longer talking to the application: they are giving orders to the operating system." },
    lead: { it: "L'endpoint <code>/exec</code> esegue il parametro <code>cmd</code> come utente <code>defender</code>. Il seme sceglie un marcatore; la verifica chiede alla shell di stamparlo insieme a <code>id</code>. Dopo l'hardening la stessa richiesta deve essere 403 e senza output.", en: "Endpoint <code>/exec</code> runs parameter <code>cmd</code> as user <code>defender</code>. The seed chooses a marker; the check asks the shell to print it together with <code>id</code>. After hardening the same request must be 403 with no output." },
    analogy: { it: "Un modulo ordini dovrebbe accettare prodotti e quantità. Se accetta anche «apri il retrobottega», il problema è il linguaggio concesso, non la singola frase.", en: "An order form should accept products and quantities. If it also accepts “open the stockroom”, the problem is the allowed language, not the one sentence." },
    shown: [{ cmd: "curl -G --data-urlencode 'cmd=id' http://10.10.0.2:8080/exec", out: "uid=1001(defender) gid=1001(defender)", note: { it: "È output prodotto sul difensore e portato via HTTP.", en: "This output is produced on the defender and carried over HTTP." } }, { cmd: "cyber-harden rce", out: "rce: hardened", note: { it: "Ora la stessa sonda deve fallire.", en: "Now the same probe must fail." } }],
    pitfalls: [{ it: "<strong>Una blacklist di <code>;</code> non chiude una shell.</strong> Pipe, sostituzioni, newline e opzioni restano un linguaggio enorme. Non costruire comandi da input non fidato.", en: "<strong>A blacklist for <code>;</code> does not close a shell.</strong> Pipes, substitutions, newlines, and options remain a huge language. Do not build commands from untrusted input." }, { it: "Eseguire come utente non-root riduce l'impatto, non elimina RCE.", en: "Running as a non-root user reduces impact; it does not eliminate RCE." }],
    pro: { it: "<p>Il processo PHP viene realmente avviato come <code>defender</code> nel suo namespace di rete. Il check non cerca <code>shell_exec</code> nel sorgente: lancia il comando e osserva se l'output attraversa ancora la rete.</p>", en: "<p>The PHP process really runs as <code>defender</code> in its network namespace. The check does not search for <code>shell_exec</code> in source: it runs a command and observes whether output still crosses the network.</p>" },
    exercise: {
        brief: { it: "Dall'attaccante esegui una volta il comando seminato in <code>~/lab/rce.txt</code>, poi abilita <code>cyber-harden rce</code> sul difensore e ripeti.", en: "From the attacker execute the command seeded in <code>~/lab/rce.txt</code> once, then enable <code>cyber-harden rce</code> on the defender and repeat." },
        come: [{ dove: "pc", testo: { it: "Osserva l'identità ottenuta prima della correzione:", en: "Observe the identity obtained before the fix:" }, cmd: "curl -G --data-urlencode \"cmd=$(cat ~/lab/rce.txt)\" http://10.10.0.2:8080/exec" }, { dove: "server", testo: { it: "Chiudi il ponte verso la shell:", en: "Close the bridge into the shell:" }, cmd: "cyber-harden rce" }, { dove: "pc", testo: { it: "Ripeti la stessa sonda:", en: "Repeat the same probe:" }, cmd: "curl -i -G --data-urlencode \"cmd=$(cat ~/lab/rce.txt)\" http://10.10.0.2:8080/exec" }],
        nota: { it: "La verifica pretende 403 e assenza sia del marcatore sia di <code>uid=</code>.", en: "The check requires 403 and absence of both the marker and <code>uid=</code>." },
        checks: [check("rce-rifiutata", "L'endpoint di esecuzione non risponde 403.", "The execution endpoint does not return 403.", "Abilita l'hardening RCE sul difensore.", "Enable RCE hardening on the defender."), check("nessun-output-comando", "La risposta contiene ancora output prodotto dalla shell.", "The response still contains shell-produced output.", "Il rifiuto deve avvenire prima di chiamare la shell.", "Reject before invoking the shell.")],
        hints: [{ it: "La sonda è già URL-encoded da curl: non riscrivere il comando.", en: "curl already URL-encodes the probe: do not rewrite the command." }, { it: "Un 403 verde senza output è più forte di una pagina che dice soltanto «errore».", en: "A 403 with no output is stronger than a page merely saying “error”." }],
    },
    recap: [riga("nessuna shell", "elimina il linguaggio d'attacco", "remove the attack language", "API strutturata", "structured API"), riga("stesso exploit", "dimostra la chiusura", "prove closure", "403 + nessun output", "403 + no output")],
});
