import { creaCapitolo, check, riga } from "../factory.js";

export default creaCapitolo({
    id: "ch03", num: 3, requires: ["ch02"],
    title: { it: "Filtrare a mano: il contatore", en: "Manual filtering: the counter" },
    oneLiner: { it: "Un attacco fallito vale poco; una regola che conta il suo pacchetto dice perché.", en: "A failed attack says little; a rule counting its packet says why." },
    commands: ["iptables -N", "iptables -A", "iptables -L -v -n"], glossary: ["catena", "REJECT", "contatore"],
    hook: { it: "«Non risponde» può voler dire servizio morto, rete rotta o filtro efficace. Il contatore separa le tre storie.", en: "“It does not answer” may mean a dead service, broken network, or effective filter. The counter separates the three stories." },
    lead: { it: "Il seed crea la catena <code>EDU-GUARD</code> davanti alla porta 9000. Tu aggiungi una regola per l'IP reale dell'attaccante. La verifica legge il contatore, lancia una nuova richiesta e lo legge di nuovo.", en: "The seed creates chain <code>EDU-GUARD</code> in front of port 9000. You add a rule for the attacker's real IP. The check reads the counter, fires a new request, and reads it again." },
    analogy: { it: "Una porta sbarrata e un citofono guasto sembrano uguali da fuori. Il tornello che scatta di uno è la ricevuta del blocco.", en: "A barred door and a broken intercom look identical from outside. A turnstile advancing by one is the block receipt." },
    shown: [{ cmd: "sudo iptables -L EDU-GUARD -v -n -x", out: "pkts bytes target  prot source      destination\n1    60    REJECT  tcp  10.10.0.1 0.0.0.0/0", note: { it: "Il numero deve crescere durante la sonda.", en: "The number must increase during the probe." } }],
    pitfalls: [{ it: "<strong>Spegnere il servizio fa fallire curl ma non difende niente.</strong> Il check pretende sia il fallimento sia un pacchetto contato dalla regola.", en: "<strong>Stopping the service makes curl fail but defends nothing.</strong> The check requires both failure and a packet counted by the rule." }, { it: "<code>DROP</code> e <code>REJECT</code> hanno effetti osservabili diversi: silenzio contro rifiuto immediato. Qui sono ammessi entrambi.", en: "<code>DROP</code> and <code>REJECT</code> have different observable effects: silence versus immediate refusal. Both are accepted here." }],
    pro: { it: "<p>Il check non cerca il comando digitato. Somma i contatori delle decisioni di blocco, provoca traffico dalla pila di rete dell'attaccante e pretende un delta positivo insieme all'assenza della risposta.</p>", en: "<p>The check does not search the typed command. It sums counters on blocking decisions, generates traffic from the attacker network stack, and requires a positive delta together with no response.</p>" },
    exercise: {
        brief: { it: "Sul difensore blocca l'accesso dell'IP <code>10.10.0.1</code> alla porta 9000 nella catena <code>EDU-GUARD</code>. Poi osserva il contatore.", en: "On the defender, block IP <code>10.10.0.1</code> from port 9000 in chain <code>EDU-GUARD</code>. Then observe the counter." },
        come: [{ dove: "server", testo: { it: "Aggiungi una decisione di blocco mirata:", en: "Add a targeted blocking decision:" }, cmd: "sudo iptables -A EDU-GUARD -s 10.10.0.1 -p tcp --dport 9000 -j REJECT" }, { dove: "pc", testo: { it: "Provala dalla rete opposta:", en: "Test it from the opposite network:" }, cmd: "curl --max-time 3 http://10.10.0.2:9000/health" }, { dove: "server", testo: { it: "Leggi i pacchetti:", en: "Read the packets:" }, cmd: "sudo iptables -L EDU-GUARD -v -n -x" }],
        nota: { it: "La verifica genera una richiesta ulteriore: uno zero non può diventare verde senza un attacco.", en: "The check generates one additional request: zero cannot turn green without an attack." },
        checks: [check("attacco-bloccato", "La sonda raggiunge ancora il servizio.", "The probe still reaches the service.", "Controlla catena, sorgente e porta.", "Check the chain, source, and port."), check("pacchetto-contato", "Nessuna regola di blocco ha contato la sonda.", "No blocking rule counted the probe.", "Guarda la colonna <code>pkts</code> prima e dopo una richiesta.", "Watch the <code>pkts</code> column before and after a request.")],
        hints: [{ it: "La regola va nel namespace del difensore: usa il terminale destro.", en: "The rule belongs in the defender namespace: use the right terminal." }, { it: "Il servizio è vivo prima del filtro; non fermarlo.", en: "The service is alive before filtering; do not stop it." }],
    },
    recap: [riga("iptables -A", "aggiunge una decisione alla catena", "add a decision to a chain", "-s, --dport, -j", "-s, --dport, -j"), riga("iptables -L -v -x", "mostra contatori esatti", "show exact counters", "leggi prima e dopo", "read before and after")],
});
