[cyber-auth]
enabled = false
filter = cyber-auth
backend = pyinotify
logpath = /run/cyber-lab/audit.log
port = 8080
protocol = tcp
maxretry = 3
findtime = 120
bantime = 300
banaction = iptables-multiport
