import { creaCapitolo, check, riga } from "../factory.js";

export default creaCapitolo({
    id: "ch07", num: 7, requires: ["ch06"],
    title: { it: "Il filtro cieco", en: "The blind filter" },
    oneLiner: { it: "Zero può voler dire pace oppure sensore rotto; soltanto un attacco noto separa i due casi.", en: "Zero may mean peace or a broken sensor; only a known attack separates the cases." },
    commands: ["fail2ban-regex", "cyber-burst", "diff"], glossary: ["failregex", "datepattern", "falso negativo"],
    hook: { it: "Tredicimila righe, zero match, nessun errore. È un risultato perfettamente valido per un filtro scritto male.", en: "Thirteen thousand lines, zero matches, no error. That is a perfectly valid result for a badly written filter." },
    lead: { it: "fail2ban rimuove il prefisso data prima di applicare <code>failregex</code>. Il filtro cieco pretende ancora la data e quindi non vede nulla. La verifica genera N eventi freschi, non un campione decorativo.", en: "fail2ban removes the date prefix before applying <code>failregex</code>. The blind filter still expects the date and therefore sees nothing. The check generates N fresh events, not a decorative sample." },
    analogy: { it: "Un metal detector che segna zero dopo che hai fatto passare una chiave non certifica una folla disarmata: certifica un collaudo fallito.", en: "A metal detector reading zero after you pass a key through it does not certify an unarmed crowd: it certifies a failed test." },
    shown: [{ cmd: "sudo fail2ban-regex audit.log cyber-blind", out: "Lines: 5 lines, 0 ignored, 0 matched, 5 missed", note: { it: "Senza attacco controllato, quello zero resta ambiguo.", en: "Without a controlled attack, that zero remains ambiguous." } }, { cmd: "sudo fail2ban-regex audit.log cyber-good", out: "Lines: 5 lines, 0 ignored, 5 matched, 0 missed", note: { it: "Stesso registro, lettore corretto.", en: "Same log, correct reader." } }],
    pitfalls: [{ it: "<strong>Aggiungere <code>.*</code> ovunque può creare falsi positivi.</strong> Qui la correzione è togliere dal regex ciò che il parser data ha già consumato.", en: "<strong>Adding <code>.*</code> everywhere may create false positives.</strong> Here the fix is removing from the regex what the date parser already consumed." }, { it: "Un file di esempio non prova la pipeline viva. Il check produce le righe attraverso la rete prima di testarle.", en: "A sample file does not prove a live pipeline. The check produces lines through the network before testing them." }],
    pro: { it: "<p>Questo riproduce l'invariante già verde nel plugin qlab: stesso log, filtro cieco a zero, filtro corretto a N. Non conclude che ogni zero sia un guasto; conclude che lo zero, da solo, non decide.</p>", en: "<p>This reproduces the invariant already green in the qlab plugin: same log, blind filter at zero, correct filter at N. It does not conclude every zero is a fault; it concludes zero alone cannot decide.</p>" },
    exercise: {
        brief: { it: "Correggi <code>/etc/fail2ban/filter.d/cyber-blind.conf</code>: il <code>failregex</code> deve riconoscere la parte rimasta dopo la rimozione della data. La verifica genererà N attacchi nuovi.", en: "Fix <code>/etc/fail2ban/filter.d/cyber-blind.conf</code>: its <code>failregex</code> must recognise what remains after date removal. The check will generate N fresh attacks." },
        come: [{ dove: "server", testo: { it: "Confronta i due filtri:", en: "Compare the two filters:" }, cmd: "sudo diff -u /etc/fail2ban/filter.d/cyber-blind.conf /etc/fail2ban/filter.d/cyber-good.conf" }, { dove: "server", testo: { it: "Porta nel filtro cieco il regex che lavora sulla riga già normalizzata:", en: "Put into the blind filter the regex that works on the already normalised line:" }, cmd: "sudo cp /etc/fail2ban/filter.d/cyber-good.conf /etc/fail2ban/filter.d/cyber-blind.conf" }],
        nota: { it: "Il numero N dipende dal seme. Il check azzera il log, attacca e pretende esattamente N match: né zero né un regex che cattura righe estranee.", en: "N depends on the seed. The check clears the log, attacks, and requires exactly N matches: neither zero nor a regex catching unrelated lines." },
        checks: [check("attacchi-presenti", "La raffica di controllo non ha prodotto N eventi nel registro.", "The control burst did not produce N events in the log.", "La porta 8080 deve essere raggiungibile prima di provare il filtro.", "Port 8080 must be reachable before testing the filter."), check("filtro-vede-n", "Il filtro non riconosce esattamente gli N attacchi reali.", "The filter does not recognise exactly the N real attacks.", "Il <code>failregex</code> deve iniziare da <code>Failed login</code>, non dalla data.", "The <code>failregex</code> must start at <code>Failed login</code>, not the date.")],
        hints: [{ it: "fail2ban-regex stampa anche le righe mancate: leggile.", en: "fail2ban-regex also prints missed lines: read them." }, { it: "Il filtro <code>cyber-good.conf</code> è il confronto esplicito, non una soluzione nascosta.", en: "Filter <code>cyber-good.conf</code> is the explicit comparison, not a hidden solution." }],
    },
    recap: [riga("fail2ban-regex", "collauda il sensore su eventi noti", "test the sensor against known events", "matched deve essere N", "matched must be N"), riga("zero", "risultato ambiguo senza stimolo", "ambiguous result without stimulus", "attacca e rimisura", "attack and measure again")],
});
